# Generated by Django 5.2.4 on 2025-09-11 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='rsvped_events', through='events.RSVP', to=settings.AUTH_USER_MODEL),
        ),
    ]
