# Generated by Django 5.2.4 on 2025-09-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Attended', 'Attended')], default='Confirmed', max_length=20),
        ),
    ]
